export const dom = {
    settingsBtn: document.getElementById('settings-btn'),
    settingsModal: document.getElementById('settings-modal'),
    settingsCloseBtn: document.getElementById('settings-close-btn'),
    topicSearch: document.getElementById('topic-search'),
    topicDropdown: document.getElementById('topic-dropdown'),

    generateBtn: document.getElementById('generate-btn'),
    audioToggleBtn: document.getElementById('audio-toggle-btn'),
    audioToggleIcon: document.getElementById('audio-toggle-icon'),
    hintBtn: document.getElementById('hint-btn'),
    loadingSpinner: document.getElementById('loading-spinner'),
    timer: document.getElementById('timer'),
    exerciseContent: document.getElementById('exercise-content'),

    englishHintEl: document.getElementById('english-hint'),
    answerArea: document.getElementById('answer-area'),
    answerPrompt: document.getElementById('answer-prompt'),
    constructedSentenceEl: document.getElementById('constructed-sentence'),
    scrambledWordsContainer: document.getElementById('scrambled-words-container'),
    feedbackArea: document.getElementById('feedback-area'),
    correctSentenceDisplay: document.getElementById('correct-sentence-display'),
    exerciseCounter: document.getElementById('exercise-counter'),
    progressBar: document.getElementById('progress-bar'),
    progressPercentage: document.getElementById('progress-percentage'),
    emptyStateContainer: document.getElementById('empty-state-container'),

    topicsList: document.getElementById('topics-list'),
    topicsSearchInput: document.getElementById('topics-search-input'),
    topicsSearchClear: document.getElementById('topics-search-clear'),
    topicSort: document.getElementById('topic-sort'),
    addTopicBtn: document.getElementById('add-topic-btn'),
    addTopicForm: document.getElementById('add-topic-form'),
    newTopicName: document.getElementById('new-topic-name'),
    newTopicPrompt: document.getElementById('new-topic-prompt'),
    saveTopicBtn: document.getElementById('save-topic-btn'),
    cancelAddBtn: document.getElementById('cancel-add-btn'),

    // Form validation elements
    newTopicNameError: document.getElementById('new-topic-name-error'),
    newTopicPromptError: document.getElementById('new-topic-prompt-error'),
    editTopicPromptError: document.getElementById('edit-topic-prompt-error'),

    // Hierarchy preview elements
    addTopicHierarchyPreview: document.getElementById('add-topic-hierarchy-preview'),
    addTopicPreviewPath: document.getElementById('add-topic-preview-path'),
    editTopicHierarchyPreview: document.getElementById('edit-topic-hierarchy-preview'),
    editTopicCurrentPath: document.getElementById('edit-topic-current-path'),

    // Recently used topics elements
    recentlyUsedTopics: document.getElementById('recently-used-topics'),
    recentTopicsContainer: document.getElementById('recent-topics-container'),
    editRecentlyUsedTopics: document.getElementById('edit-recently-used-topics'),
    editRecentTopicsContainer: document.getElementById('edit-recent-topics-container'),

    promptEditor: document.getElementById('prompt-editor'),
    currentTopicName: document.getElementById('current-topic-name'),
    promptTextarea: document.getElementById('prompt-textarea'),
    savePromptBtn: document.getElementById('save-prompt-btn'),
    cancelEditBtn: document.getElementById('cancel-edit-btn'),

    viewVersionsBtn: document.getElementById('view-versions-btn'),
    versionHistory: document.getElementById('version-history'),
    versionTopicName: document.getElementById('version-topic-name'),
    versionsList: document.getElementById('versions-list'),
    closeVersionsBtn: document.getElementById('close-versions-btn'),

    viewLastRefinedPromptBtn: document.getElementById('view-last-refined-prompt-btn'),
    lastRefinedPromptModal: document.getElementById('last-refined-prompt-modal'),
    lastRefinedPromptContent: document.getElementById('last-refined-prompt-content'),
    lastRefinedPromptCloseBtn: document.getElementById('last-refined-prompt-close-btn'),

    loginBtn: document.getElementById('login-btn'),
    logoutBtn: document.getElementById('logout-btn'),
    statsBtn: document.getElementById('stats-btn'),
    historyBtn: document.getElementById('history-btn'),
    replayAudioBtn: document.getElementById('replay-audio-btn'),
    nextExerciseBtn: document.getElementById('next-exercise-btn'),
    toggleFavoriteBtn: document.getElementById('toggle-favorite-btn'),
    favoriteBtnText: document.getElementById('favorite-btn-text'),
    skipExerciseBtn: document.getElementById('skip-exercise-btn'),
    hideExerciseBtn: document.getElementById('hide-exercise-btn'),
    exerciseControls: document.getElementById('exercise-controls'),

    statsModal: document.getElementById('stats-modal'),
    statsCloseBtn: document.getElementById('stats-close-btn'),
    statsReadyToRepeatEl: document.getElementById('stats-ready-to-repeat'),
    statsTrainedEl: document.getElementById('stats-trained'),

    historyModal: document.getElementById('history-modal'),
    historyCloseBtn: document.getElementById('history-close-btn'),
    historyTopicName: document.getElementById('history-topic-name'),
    historySummary: document.getElementById('history-summary'),
    historyTotalCount: document.getElementById('history-total-count'),
    historyReadyCount: document.getElementById('history-ready-count'),
    historySuccessRate: document.getElementById('history-success-rate'),
    historyTotalAttempts: document.getElementById('history-total-attempts'),
    historyLoading: document.getElementById('history-loading'),
    historyEmpty: document.getElementById('history-empty'),
    historyContent: document.getElementById('history-content'),
    historyPagination: document.getElementById('history-pagination'),
    historyPrevBtn: document.getElementById('history-prev-btn'),
    historyNextBtn: document.getElementById('history-next-btn'),
    historyPageInfo: document.getElementById('history-page-info'),
    historyFilterReady: document.getElementById('history-filter-ready'),
    historyFilterFavorites: document.getElementById('history-filter-favorites'),
};
