export const dom = {
    settingsBtn: document.getElementById('settings-btn'),
    accountMenu: document.getElementById('account-menu'),
    topicsAdminSection: document.getElementById('topics-admin-section'),

    generateBtn: document.getElementById('generate-btn'),
    audioToggleBtn: document.getElementById('audio-toggle-btn'),
    audioToggleIcon: document.getElementById('audio-toggle-icon'),
    voiceToggleBtn: document.getElementById('voice-toggle-btn'),
    podcastTopicName: document.getElementById('podcast-topic-name'),
    podcastFavoritesOption: document.getElementById('podcast-favorites-option'),
    podcastFavoritesOnly: document.getElementById('podcast-favorites-only'),
    podcastGenerateBtn: document.getElementById('podcast-generate-btn'),
    podcastStatus: document.getElementById('podcast-status'),
    podcastStatusText: document.getElementById('podcast-status-text'),
    podcastError: document.getElementById('podcast-error'),
    podcastResult: document.getElementById('podcast-result'),
    podcastAudio: document.getElementById('podcast-audio'),
    podcastMeta: document.getElementById('podcast-meta'),
    podcastDownloadLink: document.getElementById('podcast-download-link'),
    podcastTranscript: document.getElementById('podcast-transcript'),
    podcastTranscriptSummary: document.getElementById('podcast-transcript-summary'),
    podcastPhraseList: document.getElementById('podcast-phrase-list'),
    podcastEpisodes: document.getElementById('podcast-episodes'),
    podcastEpisodesSummary: document.getElementById('podcast-episodes-summary'),
    podcastEpisodeList: document.getElementById('podcast-episode-list'),
    podcastFeedSection: document.getElementById('podcast-feed-section'),
    podcastFeedUrl: document.getElementById('podcast-feed-url'),
    podcastFeedCopyBtn: document.getElementById('podcast-feed-copy-btn'),
    podcastFeedRegenerateBtn: document.getElementById('podcast-feed-regenerate-btn'),
    podcastFeedError: document.getElementById('podcast-feed-error'),
    voiceStatus: document.getElementById('voice-status'),
    voiceStatusLabel: document.getElementById('voice-status-label'),
    voiceTranscript: document.getElementById('voice-transcript'),
    hintBtn: document.getElementById('hint-btn'),
    loadingSpinner: document.getElementById('loading-spinner'),
    timer: document.getElementById('timer'),
    exerciseContent: document.getElementById('exercise-content'),

    englishHintEl: document.getElementById('english-hint'),
    answerArea: document.getElementById('answer-area'),
    answerPrompt: document.getElementById('answer-prompt'),
    constructedSentenceEl: document.getElementById('constructed-sentence'),
    scrambledWordsContainer: document.getElementById('scrambled-words-container'),
    scrambledWordsHeader: document.getElementById('scrambled-words-header'),
    exerciseTopicLabel: document.getElementById('exercise-topic-label'),
    feedbackArea: document.getElementById('feedback-area'),
    correctSentenceDisplay: document.getElementById('correct-sentence-display'),
    exerciseCounter: document.getElementById('exercise-counter'),
    progressBar: document.getElementById('progress-bar'),
    progressPercentage: document.getElementById('progress-percentage'),
    emptyStateContainer: document.getElementById('empty-state-container'),

    topicsList: document.getElementById('topics-list'),
    topicsSearchInput: document.getElementById('topics-search-input'),
    topicsSearchClear: document.getElementById('topics-search-clear'),
    topicSort: document.getElementById('topic-sort'),
    collapseAllBtn: document.getElementById('collapse-all-btn'),
    expandAllBtn: document.getElementById('expand-all-btn'),
    addTopicBtn: document.getElementById('add-topic-btn'),
    addTopicForm: document.getElementById('add-topic-form'),
    newTopicName: document.getElementById('new-topic-name'),
    newTopicPrompt: document.getElementById('new-topic-prompt'),
    saveTopicBtn: document.getElementById('save-topic-btn'),
    cancelAddBtn: document.getElementById('cancel-add-btn'),

    // Form validation elements
    newTopicNameError: document.getElementById('new-topic-name-error'),
    newTopicPromptError: document.getElementById('new-topic-prompt-error'),
    editTopicPromptError: document.getElementById('edit-topic-prompt-error'),

    // Hierarchy preview elements
    addTopicHierarchyPreview: document.getElementById('add-topic-hierarchy-preview'),
    addTopicPreviewPath: document.getElementById('add-topic-preview-path'),
    editTopicHierarchyPreview: document.getElementById('edit-topic-hierarchy-preview'),
    editTopicCurrentPath: document.getElementById('edit-topic-current-path'),

    // Recently used topics elements
    recentlyUsedTopics: document.getElementById('recently-used-topics'),
    recentTopicsContainer: document.getElementById('recent-topics-container'),
    editRecentlyUsedTopics: document.getElementById('edit-recently-used-topics'),
    editRecentTopicsContainer: document.getElementById('edit-recent-topics-container'),

    promptEditor: document.getElementById('prompt-editor'),
    currentTopicName: document.getElementById('current-topic-name'),
    promptTextarea: document.getElementById('prompt-textarea'),
    savePromptBtn: document.getElementById('save-prompt-btn'),
    cancelEditBtn: document.getElementById('cancel-edit-btn'),

    viewVersionsBtn: document.getElementById('view-versions-btn'),
    versionHistory: document.getElementById('version-history'),
    versionTopicName: document.getElementById('version-topic-name'),
    versionsList: document.getElementById('versions-list'),
    closeVersionsBtn: document.getElementById('close-versions-btn'),

    viewLastRefinedPromptBtn: document.getElementById('view-last-refined-prompt-btn'),
    lastRefinedPromptModal: document.getElementById('last-refined-prompt-modal'),
    lastRefinedPromptContent: document.getElementById('last-refined-prompt-content'),
    lastRefinedPromptCloseBtn: document.getElementById('last-refined-prompt-close-btn'),

    loginBtn: document.getElementById('login-btn'),
    logoutBtn: document.getElementById('logout-btn'),
    offlineCacheSection: document.getElementById('offline-cache-section'),
    offlineCacheBtn: document.getElementById('offline-cache-btn'),
    offlineCacheStatus: document.getElementById('offline-cache-status'),
    offlineCacheCount: document.getElementById('offline-cache-count'),
    offlineCacheProgress: document.getElementById('offline-cache-progress'),
    offlineCacheProgressFill: document.getElementById('offline-cache-progress-fill'),
    offlineCacheProgressText: document.getElementById('offline-cache-progress-text'),
    prefSound: document.getElementById('pref-sound'),
    prefAutoplay: document.getElementById('pref-autoplay'),
    prefVoice: document.getElementById('pref-voice'),
    prefVoiceRow: document.getElementById('pref-voice-row'),
    replayAudioBtn: document.getElementById('replay-audio-btn'),
    nextExerciseBtn: document.getElementById('next-exercise-btn'),
    toggleFavoriteBtn: document.getElementById('toggle-favorite-btn'),
    favoriteBtnText: document.getElementById('favorite-btn-text'),
    explainBtn: document.getElementById('explain-btn'),
    explanationContainer: document.getElementById('explanation-container'),
    explanationText: document.getElementById('explanation-text'),
    skipExerciseBtn: document.getElementById('skip-exercise-btn'),
    skipDialog: document.getElementById('skip-dialog'),
    skipSessionBtn: document.getElementById('skip-session-btn'),
    skipRemoveBtn: document.getElementById('skip-remove-btn'),
    skipCancelBtn: document.getElementById('skip-cancel-btn'),
    toastRoot: document.getElementById('toast-root'),
    confirmDialog: document.getElementById('confirm-dialog'),
    exerciseControls: document.getElementById('exercise-controls'),
    completionStatusIndicator: document.getElementById('completion-status-indicator'),


    // Database stats
    dbStatsSection: document.getElementById('db-stats-section'),
    dbStatsContainer: document.getElementById('db-stats-container'),
    dbStatsLoading: document.getElementById('db-stats-loading'),
    dbStatsContent: document.getElementById('db-stats-content'),
    dbStatsError: document.getElementById('db-stats-error'),
    dbStatExercises: document.getElementById('db-stat-exercises'),
    dbStatTopics: document.getElementById('db-stat-topics'),
    dbStatDbSize: document.getElementById('db-stat-db-size'),
    dbStatAudioCache: document.getElementById('db-stat-audio-cache'),
    dbStatsPerTopic: document.getElementById('db-stats-per-topic'),

    // CLI access (admin only)
    cliAccessSection: document.getElementById('cli-access-section'),
    cliTokenLabel: document.getElementById('cli-token-label'),
    cliTokenGenerateBtn: document.getElementById('cli-token-generate-btn'),
    cliTokenResult: document.getElementById('cli-token-result'),
    cliTokenValue: document.getElementById('cli-token-value'),
    cliTokenCopyBtn: document.getElementById('cli-token-copy-btn'),
    cliTokenError: document.getElementById('cli-token-error'),
};
